import { SavedMeal } from "./types";

export const savedMeals: SavedMeal[] = [
  {
    id: "friday-pizza",
    name: "Friday Pepperoni Pizza",
    restaurant: "Tony's Pizzeria",
    emoji: "\u{1F355}",
    gradient: "from-orange-400 via-red-400 to-rose-500",
    mainIngredients: ["Pepperoni", "Mozzarella", "San Marzano Sauce"],
    price: 14.5,
    tax: 1.28,
    calories: 820,
    fullIngredients: [
      "Hand-tossed dough",
      "San Marzano tomato sauce",
      "Whole-milk mozzarella",
      "Pepperoni",
      "Oregano",
      "Olive oil",
    ],
    dietary: ["Contains pork"],
    allergens: ["Gluten", "Dairy"],
    pickupEtaMinutes: 12,
  },
  {
    id: "tikka-bowl",
    name: "Chicken Tikka Bowl",
    restaurant: "Spice Route",
    emoji: "\u{1F35B}",
    gradient: "from-amber-400 via-orange-400 to-red-400",
    mainIngredients: ["Grilled Chicken", "Basmati Rice", "Tikka Masala"],
    price: 12.95,
    tax: 1.14,
    calories: 690,
    fullIngredients: [
      "Basmati rice",
      "Marinated chicken thigh",
      "Tikka masala sauce",
      "Grilled peppers",
      "Cilantro",
      "Yogurt drizzle",
    ],
    dietary: ["Gluten-free"],
    allergens: ["Dairy"],
    pickupEtaMinutes: 15,
  },
  {
    id: "oat-latte",
    name: "Oat Milk Latte + Croissant",
    restaurant: "Corner Cafe",
    emoji: "☕",
    gradient: "from-yellow-200 via-amber-300 to-orange-400",
    mainIngredients: ["Double Espresso", "Oat Milk", "Butter Croissant"],
    price: 8.25,
    tax: 0.73,
    calories: 430,
    fullIngredients: [
      "Double espresso",
      "Steamed oat milk",
      "Butter croissant",
    ],
    dietary: ["Vegetarian"],
    allergens: ["Gluten", "Tree nuts (may contain)"],
    pickupEtaMinutes: 6,
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    restaurant: "Bangkok Kitchen",
    emoji: "\u{1F35C}",
    gradient: "from-lime-400 via-yellow-400 to-amber-500",
    mainIngredients: ["Rice Noodles", "Shrimp", "Peanuts"],
    price: 13.75,
    tax: 1.21,
    calories: 750,
    fullIngredients: [
      "Rice noodles",
      "Shrimp",
      "Egg",
      "Bean sprouts",
      "Crushed peanuts",
      "Tamarind sauce",
    ],
    dietary: ["Pescatarian"],
    allergens: ["Peanuts", "Shellfish", "Egg"],
    pickupEtaMinutes: 14,
  },
];
